# SPDX-License-Identifier: GPL-3.0-or-later

NONE = None

VIDEO = "video"
MOVIE = "movie"
TVSHOW = "tvshow"
SEASON = "season"
EPISODE = "episode"
MUSICVIDEO = "musicvideo"
VIDEO_TYPES = {VIDEO, MOVIE, TVSHOW, SEASON, EPISODE, MUSICVIDEO}

AUDIO = "music"  # Make it more in line with a generic VIDEO type.
MUSIC = "music"
SONG = "song"
ALBUM = "album"
ARTIST = "artist"
AUDIO_TYPES = {MUSIC, SONG, ALBUM, ARTIST}

ALL = {VIDEO, MOVIE, TVSHOW, SEASON, EPISODE, MUSICVIDEO, MUSIC, SONG, ALBUM, ARTIST}
FOLDER_TYPES = {TVSHOW, SEASON, ALBUM, ARTIST}
PLAYABLE_TYPES = {VIDEO, MOVIE, EPISODE, MUSICVIDEO, MUSIC, SONG}
